### ISSUE TITLE
Problème de création de dossier

### ISSUE THREAD

**Issue by dNicolle** [AwebsomeFr/cirrus#3]
Hello,

Depuis la MAJ que j'ai faite, le champs qui me permettait de créer des dossier ne permet plus d'en créer, mais fait simplement une recherche.

Merci :)

**Comment by AwebsomeFr** [comment]
Hello Dominique,

C'est tout à fait normal. Le comportement du champ en question a en effet été revu pour être simplifié, au moins dans un premier temps. Par défaut, saisir dans le champ effectue désormais une recherche dans le dossier courant. Il faut faire précéder d'un signe + la requête pour passer en mode création de dossier.

Par exemple : 
_nom du dossier à rechercher_ > recherchera effectivement une correspondance, sans avoir besoin de valider.
_+nom du dossier à créer_ > créera le dossier en question à la soumission.

Pour information, il y a une infobulle qui le précise au survol du champ. La documentation est en cours de rédaction à ce sujet : j'essaie de me pencher rapidement sur ce point essentiel.
